### ISSUE TITLE
Oanvända filer

### ISSUE THREAD

**Issue by Degota** [greyhatcave/GodotGame-1.2#12]
Försökte fixa bullet start position och det var svårt att hänga med, flera filer som jag misstänker inte används. 
Används dessa filer?
- flame collision?
- george bullet?
Sen fanns det två statemachine filer tror ena är fel skapad bara

**Comment by Ario124** [comment]
Hej,

Ang bullet start pos så tror jag att man bör kolla på player.tscn / Firepointer.

Jag förstår att det kan va rörigt att ge sig in i alla filer som heter lite random xD

Fienden som är gul i färg har jag döpt till 'George' men kan hända att den filen fortfarande heter 'Enemy_Yellow.tscn'
Script till denna fiende heter 'George.gd'

- Flame Collision används för att bekräfta att spelaren är träffad av den för att senare starta particles2d.emitting, du kan ändra hur du vill om du kan få igång Flamethrower med dmg, borde grymt 👍 

- George Bullet är som du skrev om lite, att de e dubbla filer för att separera från player bullet o enemy bullet med olika utseeden/dmg. Man kanske ska ha en fil som delas delvis av enemies/player.

- StateMachine såg jag nu fanns 2 av på George scenen, tror däremot att det går bra att ta bort den som heter 'StateMachine' o behålla EnemyFSM. Jag har använt mig av 2 olika för att skilja Player o Enemy states. Det har varit rörigt att koppla dessa till filer, testa gärna så att du kan göra dig av med den som inte används och att allt fungerar som det ska.

**Comment by Degota** [comment]
Kan kika vidare på hur man kan göra för att samla ihop det på ett bra sätt så det inte blir rörigt.
Förstår att det blir ogenontänkt när man testar. Det är lugnt!
